all:	default

default: digitSum.o arrayOut.o linearSum.o factorial.o zeroCount.o minimalArray.o
	g++ digitSum.o arrayOut.o linearSum.o factorial.o zeroCount.o minimalArray.o -o exec

digitSum.o: digitSum.cpp
	g++ -c digitSum.cpp

arrayOut.o: arrayOut.cpp
	g++ -c arrayOut.cpp

linearSum.o: linearSum.cpp
	g++ -c linearSum.cpp

factorial.o: factorial.cpp
	g++ -c factorial.cpp

zeroCount.o: zeroCount.cpp
	g++ -c zeroCount.cpp

minimalArray.o: minimalArray.cpp
	g++ -c minimalArray.cpp
